---
title: Heitor Colangelo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
paginate: 100
language: en-uk
words_per_minute: 200
description: Code chaos, travel tales, and guitar antics. This is a wild ride where
  bugs, snapshots,  and wrong chords unite for a comically charming experience!
baseurl: "/"
url: https://heitorcolangelo.dev
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
CNAME: heitorcolangelo.dev
navigation: true
subscribers: false
twitter_username: heitorcolangelo
github_username: heitorcolangelo
disqus: false
disqus_shortname: heitorcolangelo
google_analytics: UA-69281367-1
permalink: "/:title"
plugins_dir:
- _plugins
plugins:
- jekyll-paginate
- jekyll-feed
feed:
  path: feed.xml
safe: false
lsi: false
username: heitorcolangelo
repo: heitorcolangelo
branch: master
relative_source: "../heitorcolangelo/"
destination: _site
production_url: https://heitorcolangelo.dev
source_url: https://github.com/heitorcolangelo/heitorcolangelo.github.io
exclude:
- assets/css
- node_modules
- vendor
- ".travis.yml"
- Gemfile
- Gemfile.lock
- GHOST.txt
- gulpfile.js
- LICENSE
- package.json
- package-lock.json
- Rakefile
- README.md
- script.py
- changelog.md
- "*.Rmd"
- ".git*"
